# SPDX-License-Identifier: Apache-2.0
set(ZAT_ROOT ${CMAKE_CURRENT_LIST_DIR}/..)
if(DEFINED WEST_TOPDIR)
  set(FUURIN_DEP_ROOT ${WEST_TOPDIR})
else()
  set(FUURIN_DEP_ROOT ${ZAT_ROOT}/..)
endif()
set(ZAT_LIBFVAD_DIR "${FUURIN_DEP_ROOT}/modules/lib/libfvad" CACHE PATH "libfvad source")
if(NOT EXISTS "${ZAT_LIBFVAD_DIR}/src/CMakeLists.txt")
  message(FATAL_ERROR "Missing libfvad at ${ZAT_LIBFVAD_DIR}; run west update libfvad")
endif()
if(NOT TARGET fvad)
  add_subdirectory(${ZAT_LIBFVAD_DIR}/src ${CMAKE_CURRENT_BINARY_DIR}/zat-fvad)
endif()
target_compile_features(fvad PUBLIC c_std_11)

if(TARGET zephyr_interface)
  if(NOT CONFIG_FUURIN_AUDIO_AEC)
    set(ZAT_AEC_BACKEND NONE)
  elseif(CONFIG_FUURIN_AUDIO_AEC_BACKEND_AECM)
    set(ZAT_AEC_BACKEND AECM)
  else()
    set(ZAT_AEC_BACKEND SPEEXDSP)
  endif()
else()
  set(ZAT_AEC_BACKEND SPEEXDSP CACHE STRING "AEC backend: SPEEXDSP or AECM")
  set_property(CACHE ZAT_AEC_BACKEND PROPERTY STRINGS SPEEXDSP AECM)
endif()

if(ZAT_AEC_BACKEND STREQUAL "NONE")
  set(aec_target "")
  set(aec_source ${ZAT_ROOT}/src/aec_none.c)
elseif(ZAT_AEC_BACKEND STREQUAL "AECM")
  enable_language(CXX)
  include(${CMAKE_CURRENT_LIST_DIR}/aecm.cmake)
  set(aec_target zat_webrtc_aecm)
  set(aec_source ${ZAT_ROOT}/src/aec_aecm.c)
elseif(ZAT_AEC_BACKEND STREQUAL "SPEEXDSP")
  set(ZAT_SPEEXDSP_DIR "${FUURIN_DEP_ROOT}/modules/lib/speexdsp" CACHE PATH "SpeexDSP source")
  if(NOT EXISTS "${ZAT_SPEEXDSP_DIR}/libspeexdsp/mdf.c")
    message(FATAL_ERROR "Missing SpeexDSP at ${ZAT_SPEEXDSP_DIR}; run west update speexdsp")
  endif()
  add_library(zat_speexdsp STATIC
    ${ZAT_SPEEXDSP_DIR}/libspeexdsp/mdf.c
    ${ZAT_SPEEXDSP_DIR}/libspeexdsp/fftwrap.c
    ${ZAT_SPEEXDSP_DIR}/libspeexdsp/kiss_fft.c
    ${ZAT_SPEEXDSP_DIR}/libspeexdsp/kiss_fftr.c
    ${ZAT_ROOT}/src/speex_alloc.c)
  target_include_directories(zat_speexdsp PUBLIC
    ${ZAT_SPEEXDSP_DIR}/include ${CMAKE_CURRENT_LIST_DIR}/speex)
  target_compile_definitions(zat_speexdsp PRIVATE FIXED_POINT USE_KISS_FFT EXPORT= OS_SUPPORT_CUSTOM)
  target_compile_features(zat_speexdsp PRIVATE c_std_11)
  set(aec_target zat_speexdsp)
  set(aec_source ${ZAT_ROOT}/src/aec.c)
else()
  message(FATAL_ERROR "ZAT_AEC_BACKEND must be SPEEXDSP or AECM")
endif()

add_library(fuurin_audio_pipeline STATIC ${aec_source}
  ${ZAT_ROOT}/src/vad.c ${ZAT_ROOT}/src/pipeline.c ${ZAT_ROOT}/src/render_history.c)
target_include_directories(fuurin_audio_pipeline PUBLIC ${ZAT_ROOT}/include)
target_link_libraries(fuurin_audio_pipeline PUBLIC fvad ${aec_target})
if(TARGET zephyr_interface)
  target_link_libraries(fvad PRIVATE zephyr_interface)
  if(aec_target)
    target_link_libraries(${aec_target} PRIVATE zephyr_interface)
  endif()
  target_link_libraries(fuurin_audio_pipeline PRIVATE zephyr_interface)
endif()
